[package]
name = "exofetch-rs"
version = "0.1.0"
authors = ["Vinícius R. Miguel <36349314+vrmiguel@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc    = "0.2.79"
colored = "2"

[dependencies.whoami]
path = "whoami"