max_width = 100
comment_width = 80
merge_imports = true
match_block_trailing_comma = true
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
edition = "2018"
enum_discrim_align_threshold = 12
struct_field_align_threshold = 12

unstable_features = true
format_strings = true
wrap_comments = true
